### ISSUE TITLE
Feedback on database structure

### ISSUE THREAD

**Issue by gabescarbrough** [ga-wdi-boston/group-project#152]
@dvdpwll @echoxin and I have been discussing the best way to structure our database and we will have a couple different ideas.

We're unsure how references to other models by ID work exactly and would like to discuss our different ideas for our models to get feedback.

Could @gaand, @laurenfazah or @J-Weeks meet with us for a one-on-one (three-on-one?) today to discuss?

**Comment by laurenfazah** [comment]
Could you provide more insight into the modeling routes you're considering taking?

**Comment by gabescarbrough** [comment]
We have two ideas, @laurenfazah.

The first is one user which reference many folders by ID, one folder references many files by ID. Users, folders and files each have their own model. (green)

The second is one user has one filingCabinet (which has objects which represent folders within it) which references many files by ID. The models would be user, filingCabinet and file. (red)

Our consensus is that option two seems to fit the MongoDB line of thinking more, but since we don't fully understand how references are done in MongoDB, option one might be clearer because each folder has its own model.

![ERD](http://i.imgur.com/KH6Ss7W.jpg)

**Comment by laurenfazah** [comment]
I think these are both on the right track - I would lean closer to your green model since a file cabinet would likely also have many folders. Plus, your green model would more easily allow for multiple users to access certain folders, rather than folders in a single user's cabinet.

I'd suggest you all look into MongoDB's materialized paths. Read through this https://docs.mongodb.com/manual/tutorial/model-tree-structures-with-materialized-paths/, and it should easily push you in the right direction for that DB model.

**Comment by gaand** [comment]
Also:

http://blog.mongodb.org/post/87200945828/6-rules-of-thumb-for-mongodb-schema-design-part-1
http://blog.mongodb.org/post/87892923503/6-rules-of-thumb-for-mongodb-schema-design-part-2
http://blog.mongodb.org/post/88473035333/6-rules-of-thumb-for-mongodb-schema-design-part-3

**Comment by gabescarbrough** [comment]
Based on reading these links we plan to go for the green ERD.

One user references many folders by ID, one folder references many files by ID. Users, folders and files each have their own model.

We also plan to utilize materialized paths.
