### ISSUE TITLE
Question about how to organize files in FileBucket

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/group-project#240]
@moshiko1988 @ddobson @yenpraja610 and I are trying to plan our app. One of the requirements is that there be some kind of organization for the files uploaded to our file bucket. We are debating whether or not it makes more sense to use tags, implemented as an array attribute on our upload model, or some kind of file model which would have an array of the IDs of the files in it. We're currently leaning towards using tags, but don't have much of a basis for that decision other than thinking it is probably more simple.

What we realized we don't have is a good understanding of which approach would be more complex, which is something we need to know in order to make this decision

**Comment by s0phi4** [comment]
Instead of file model we meant folder model.

**Comment by raq929** [comment]
I feel like option 2 is less complex (having folders that hold an array of file_Ids). Because then you don't have to find all the files associated with a tag. But it sounds like you've already started with the tag option, which I think is nicer for users, so unless you run into a big blocker on it, I think go for it.

**Comment by samordonez** [comment]
Acknowledged.
