### ISSUE TITLE
Question: Merging branches

### ISSUE THREAD

**Issue by sstone72389** [ga-wdi-boston/group-project#303]
During our git lesson, I believe we were instructed not to merge via pull requests directly from GitHub. Is there a resource denoting the best practice for merging branches to ensure we are correctly completing this? I know there are some answers on google, pertaining to this, but we want to be sure we're following best practices. Thank you!!

**Comment by prankmode** [comment]
there's a big description of what they want us to do in the git-workflows-teams training we did.

**Comment by sstone72389** [comment]
Thanks @prankmode. I have been reviewing this. I am specifically wondering about merging pull requests, as @BenGitsCode told us that we should not accept pull requests directly from git hub. I do not see any specifics on the provided documentation about this.

**Comment by BenGitsCode** [comment]
@sstone72389 You can merge on github directly, the instructional steam stopped doing that because of github side effects. The choice is absolutely yours, I always prefer merging through the command line.

The section @prankmode is referring to is all that's required. 

What about merging pull requests did you have a question about @sstone72389?

**Comment by sstone72389** [comment]
Thanks @prankmode and @BenGitsCode. That is all I need to know.
